version: '3.4'

services:
  sportdb:
    image: postgres

  profiledb:
    image: mcr.microsoft.com/mssql/server

  sport.api:
    image: ${DOCKER_REGISTRY-}sportapi
    build:
      context: .
      dockerfile: microservices/Services/Sport/Sport.API/Dockerfile

volumes:
  postgres_sport: