version: '3.4'

services:
  sportdb:
    container_name: sportdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SportDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_sport:/var/lib/postgresql/data/

  profiledb:
    container_name: profiledb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
    restart: always
    ports:
      - "1433:1433"