version: '3.4'

services:
  sportdb:
    container_name: sportdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SportDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_sport:/var/lib/postgresql/data/