services:
  sportybuddies.api:
    environment:
      - DOTNET_ENVIRONMENT=Docker
    image: sportybuddies.api
    build:
      context: .
      dockerfile: src/SportyBuddies.Api/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - sportybuddies.db
      - sportybuddies.redis

  sportybuddies.db:
    image: postgres:latest
    container_name: sportybuddies.db
    environment:
      - POSTGRES_DB=sportybuddies
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - ./.containers/database/sportybuddies:/var/lib/postgresql/data
    ports:
      - "5432:5432"
        
  sportybuddies.seq:
    image: datalust/seq:latest
    container_name: sportybuddies.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8081:80"

  sportybuddies.redis:
    image: redis:latest
    container_name: sportybuddies.Redis
    restart: always
    ports:
      - "6379:6379"