services:
  sportybuddies.api:
    environment:
      - DOTNET_ENVIRONMENT=Docker
    image: sportybuddies.api
    build:
      context: .
      dockerfile: src/SportyBuddies.Api/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - sportybuddies.db
      - sportybuddies.redis

  sportybuddies.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sportybuddies.db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
    ports:
      - "1433:1433"
        
  sportybuddies.seq:
    image: datalust/seq:latest
    container_name: sportybuddies.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8081:80"

  sportybuddies.redis:
    image: redis:latest
    container_name: sportybuddies.Redis
    restart: always
    ports:
      - "6379:6379"