FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["microservices/Services/Sport/Sport.API/Sport.API.csproj", "microservices/Services/Sport/Sport.API/"]
COPY ["microservices/BuildingBlocks/BuildingBlocks/BuildingBlocks.csproj", "microservices/BuildingBlocks/BuildingBlocks/"]
RUN dotnet restore "microservices/Services/Sport/Sport.API/Sport.API.csproj"
COPY . .
WORKDIR "/src/microservices/Services/Sport/Sport.API"
RUN dotnet build "Sport.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Sport.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Sport.API.dll"]
